### ISSUE TITLE
Be able to define properties for install

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-hpc#359]
Feedback:

> - Feature: being able to specify a generic `gpu` recipe property (ideally alias by alias), and then defining what this implies in a site specific manner, e.g. via `settings.yaml` (e.g. `--nv` or `--rocm` depending on the available hardware)

This is a great idea - if we can define generic recipe properties, we can ask to build a recipe with them. An easy way to do this would be akin to how spack adds variants, e.g.,

```bash
$ shpc install biocontainers/fastqc+gpu
```
Would say "use the settings.yaml file to look for the "gpu" variant, and add these properties to the build. The question comes down to how to add them to the template - right now you can add options to a recipe (e.g. extra flags like --nv) but probably we would want to support different named property types, like:

```
# settings.yaml
properties:
  options:
   gpu: --nv
```
Would this be something that needs more logic than that? E.g., how to distinguish nv or rocm? And would the container be installed with this hard coded, or would the idea be to try and support runtime differences? (I'm not sure how I would do the latter because the module template is generated once. I can maybe look into if / else statements for templates, is that an idea?

**Comment by marcodelapierre** [comment]
Ideally I would love to add those extra bits of logic.
Also, let me clarify the context of my thinking: my key idea was to abstract away the need for knowing the gpu specific requirements of the various container runtimes (singularity has --nv and --rocm, other engines might have other requirements...). So I'd like to enable sys-admins and recipe developers to reason in high-level terms:
- sys-admin: what's the gpu configuration in my cluster?
- recipe developer: does my container need a gpu?

Let me share what I had in mind ideally.

In settings.yaml, a `gpu` property, that can have 3 or 4 values:
```
null or ''  # no gpu
nvidia
amd
$variable
```
This way we use settings to define properties of the cluster we're running on.
The only case where we need $variable is a cluster that has both nvidia and rocm partitions, or systems, then one would define the right variable value at runtime (e.g. in the script: variable=nvidia, or variable=amd).

Then, as a 1st round I would think that needing a GPU or not is a property of the container, so this property would go in the container.yaml. I think of 2 possibilities of implementing this:
container.yaml option 1, a simple container property: (defaults to false, or null)
```
gpu: true
```
or option 2, distinguishing between which binaries need gpus and which don't:
```
aliases:
  /x
  /y
gpu-aliases:
  /w
  /ww
```
For instance, the NGC Gromacs container (if I remember correctly) has only some commands that need the GPU.
Why going complicated with the 2nd option? To avoid `singularity` printing the warning that "no Nvidia driver was found".
It's probably overthinking it, it's only a warning...and the 1st syntax is friendlier for recipe developers.
...you're the Singularity super-guru, what do you think @vsoch ? :-)

Finally, how is the information above used by `shpc`?
When the gpu option is found in the container.yaml, the phase of modulefile creation changes.
In the example of singularity, shpc knows that:
1. if settings.yaml has gpu=nvidia, shpc will add --nv to the modulefile
2. if settings.yaml has gpu=amd, it will add --rocm

3. if settings.yaml has gpu=null ... ?? it might perhaps create the standard modulefile, and print a warning during modulefile creation, that some aliases might not work because no gpu configuration was found in the settings

4. if setting.yaml has a $variable, it depends on how we want to implement it:
   a. variable has to be nvidia/amd: then we need to implement an if logic in the modulefile (this complicates the modulefile, but preserves consistency with the other options)
   b. variable has to be --nv/--rocm: then the module will add something in the lines of \$variable (this is cleaner, but inconsistent)

Thoughts?

**Comment by vsoch** [comment]
Ah I see - so there are two variables here:

1. the definitions in a container.yaml to say "this command needs gpu"
2. the deployment global settings in settings.yaml to say "this cluster has gpu"

I can see arguments for both ways, and let me lay out my thinking. Currently, we do have some support for adding a gpu command to a container.yaml file. It's via the generic "options" setup of an alias, which looks like this:

```
docker: nvcr.io/nvidia/digits
url: https://ngc.nvidia.com/catalog/containers/nvidia:digits/tags
maintainer: '@vsoch'
description: The NVIDIA Deep Learning GPU Training System (DIGITS) puts the power
  of deep learning into the hands of engineers and data scientists.
latest:
  21.05-tensorflow-py3: sha256:92132672c1d985ebdfad13089cb1ead353e96df960788eed4b6eafd932613546
tags:
  21.02-tensorflow-py3: sha256:f5973e9b4a4424b4d394d7c42cf0aee5259dbdcce58d8a9815fae081ce99020f
  21.03-tensorflow-py3: sha256:ad2aa71d8650ea403437f86fc9a33760af8a20d980f64d660e8ef649e0d9296d
  21.04-tensorflow-py3: sha256:b72344b124b07742f5a908566c5f1905edc3d58956e446db925cf153facdf9f9
  21.05-tensorflow-py3: sha256:92132672c1d985ebdfad13089cb1ead353e96df960788eed4b6eafd932613546
filter:
- 21*
aliases:
- name: python
  command: /usr/bin/python
  options: --nv
```
I did it this way because I'd assume most people using an nvidia container would want gpu, hence the --nv flag. Of course if the user doesn't have GPU, the worst thing that happens here is a warning message (which I think is okay). But you're right, this doesn't really make it flexible to add the flag in the case that the recipe supports it and the cluster supports it. We would need to have the container declare that it's GPU compatible in the container.yaml _and_ the settings file to also say that. So let's say we take an approach of defining these properties in the settings.yaml and the container.yaml. What about clusters where there are gpus on some nodes but not others? The admin would be forced to make a yes/no decision, and again the worst thing would be adding --nv for a node that doesn't support it and getting a warning. So - I do think I'm leaning toward having properties like gpu be defined on the level of the container (and not command) because there is less risk to adding it and then getting a warning vs. not adding it and then the container doesn't work at all.

This also brings to mind another issue, that my current method of having options with `--nv` is not going to work given that we add other container technologies (for example, I'd eventually like to add Podman). but having gpu: true would work because then the container technology would render a template specific to it's ask for GPU.

I don't totally understand the settings.yaml having a $variable - where is that variable defined? Is the idea that there needs to be some logic in the modulefile to do an "if this then X, else Y?" I think in most cases just having settings.yaml --> gpu as nvidia, amd, or null will suffice. Are you thinking of clusters with nodes with different kinds of gpus?

**Comment by vsoch** [comment]
I'm thinking we should have a "features" section in both the container.yaml and settings.yaml, so in the container.yaml it would look like:

```yaml
features:
  gpu: true
```
This would not be required, but given that it's provided, would be validated to be known features and a boolean or null value. Then in the settings.yaml, we would want the same structure, but maybe named to be explicitly clear:

```yaml
container_features:
  gpu: nvidia # one of nvidia, amd defaults to null
```
And I'm also thinking that since this template needs to be container specific, it should probably be owned and rendered by the container class (e.g., we have a SingularityContainer class, and I'd like to eventually have a PodmanContainer class.

**Comment by vsoch** [comment]
And one more question for you @marcodelapierre! If we would eventually add podman, does the name shpc even make sense? Is there a better (more general name) to call it, before the project gets more widely used?

**Comment by vsoch** [comment]
Actually just thinking about the name now, technically singularity can mean a "single thing to rule them all" so it wouldn't be terrible if we added additional container technologies.  it would just mean that we are using the term here to mean what it was intended to mean for the singularity software.

**Comment by vsoch** [comment]
okay, properties are added to #367 !

**Comment by marcodelapierre** [comment]
> I'm thinking we should have a "features" section in both the container.yaml and settings.yaml, so in the container.yaml it would look like:
> 
> ```yaml
> features:
>   gpu: true
> ```
> 
> This would not be required, but given that it's provided, would be validated to be known features and a boolean or null value. Then in the settings.yaml, we would want the same structure, but maybe named to be explicitly clear:
> 
> ```yaml
> container_features:
>   gpu: nvidia # one of nvidia, amd defaults to null
> ```
> 
> And I'm also thinking that since this template needs to be container specific, it should probably be owned and rendered by the container class (e.g., we have a SingularityContainer class, and I'd like to eventually have a PodmanContainer class.

I second your reasoning, and I think your suggestion of API cited above is perfect for the purpose.

One suggestion: maybe rather than `features` (settings.yaml) vs `container_features` (container.yaml), I'd go with `system_features` or similar (settings) vs `features` (container), to reduce typing when writing container recipes :-D 

I think we can forget about the $variable idea (with conditionals in the modulefile), yes I put it there as a possible way to tackle deployments with both AMD and Nvidia GPUs, but it's probably an unnecessary complication, especially to start with (is there anyone needing it? we'll see..)

**Comment by marcodelapierre** [comment]
As regards the tool name, what might not be general in SHPC is also the "HPC" bit, as the tool could be used to quickly deploy containerised stuff in other environments; although it's true that modules are a traditional signature of HPC infrastructures. Personally, I find your usage of "Container Modules" highly meaningful in this space ... CMod?

All of this being said though...if the justification for the current name is a "single thing to rule them all", that's it, you've got me, no more questions asked, no more objections raised! (I am a huge LOTR fan)

**Comment by vsoch** [comment]
>  One suggestion: maybe rather than features (settings.yaml) vs container_features (container.yaml), I'd go with system_features or similar (settings) vs features (container), to reduce typing when writing container recipes :-D

Oh I think the implementation is reversed - settings.yaml has container_features and container.yaml has just features (because it's implied they are container features!). I was more specific in settings.yaml because you could imagine there are different kinds of features.

Doing a quick [search for cmod](https://www.google.com/search?channel=fs&client=ubuntu&q=cmod) I think there are a lot of things with that name, so I'm good with shpc!

**Comment by marcodelapierre** [comment]
> Oh I think the implementation is reversed - settings.yaml has container_features and container.yaml has just features (because it's implied they are container features!). I was more specific in settings.yaml because you could imagine there are different kinds of features.

Makes perfect sense, thanks for clarifying!

On SHPC, as I said I really love the explanation for Singularity therein ;)

**Comment by vsoch** [comment]
This is added! We will need to think about what gpu means for podman/docker, and what other features might be defined, period, but for now this is safe to close.

**Comment by marcodelapierre** [comment]
That's super cool!

Just sharing thoughts down here, for future reference (hopefully they're somehow useful).

One thing I have learnt recently about Podman is that configurations for stuff like MPI (and probably GPU) can be coded by sys admins in the podman configs, so that they work out-of-the-box at runtime. Haven't got the chance to test setups enough, so right now I am unable to advise on typical setup scenarios with Podman.

This being said, 
for GPU and docker/podman, I think there is some flag to enable usage of an Nvidia container (dunno for AMD .. will know at some point as we're getting a quite large Instinct cluster here :-)  )
Some links:
- https://github.com/NVIDIA/nvidia-docker
- https://www.redhat.com/en/blog/how-use-gpus-containers-bare-metal-rhel-8

Shifter and Sarus don't need a flag if I remember correctly.

Another natural property might be MPI; here Singularity is good to go, Podman needs lots of flags, Shifter/Sarus need `--mpi` typically.
Then other things could be provided, with the idea of abstracting away the need for explicit user configurations with flags... for instance, there could be a property to control whether shell environment is insulated or shared with the host...
