### ISSUE TITLE
shpc test bug when using non null singularity_module in settings.yaml

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#368]
**Describe the bug**
shpc test fails for me when setting a singularity environment to be loaded

**To Reproduce**

in settings.yaml, set a non null singularity_module, e.g.
```
singularity_module: singularity
```
or 
```
singularity_module: singularity/3.6.4
```
Run shpc test:
```
shpc test biocontainers/fastqc
```
Output:
```
Module biocontainers-fastqc/v0.11.5 was created.

Inactive Modules:
  1) gcc     2) go     3) pawseytools     4) python/3.6.3     5) sandybridge     6) singularity     7) slurm

Testing load of biocontainers/fastqc:v0.11.5
Lmod has detected the following error: The following module(s) are unknown: "singularity"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "singularity"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "singularity" which failed while processing the following module(s):

    Module fullname                      Module Filename
    ---------------                      ---------------
    biocontainers/fastqc/v0.11.5/module  /tmp/shpc-test.931erlfy/biocontainers/fastqc/v0.11.5/module.lua


Test of biocontainers/fastqc was not successful.

```

**Expected behavior**
(obtained when singularity_module is left blank '' )

```
Module biocontainers-fastqc/v0.11.5 was created.

Inactive Modules:
  1) gcc     2) go     3) pawseytools     4) python/3.6.3     5) sandybridge     6) singularity     7) slurm

Testing load of biocontainers/fastqc:v0.11.5
Module biocontainers-fastqc/v0.11.9_cv8 was created.

Inactive Modules:
  1) gcc     2) go     3) pawseytools     4) python/3.6.3     5) sandybridge     6) singularity     7) slurm

Testing load of biocontainers/fastqc:v0.11.9_cv8

```

**Version of Singularity and Singularity Registry HPC Client**
singularity/3.6.4
shpc 0.0.24, commit d70803e2b459a5fb7e7623767fe1ec456c0f0f4c
Anything else?

for reference, here's my singularity module file (LUA), file called "3.6.4.lua":

```
help("Sets up the paths you need to use singularity version 3.6.4")
local version = '3.6.4'
local build_options = 'default'
local tool = 'singularity'
whatis( [[Singularity enables users to have full control of their environment. Singularity 
containers can be used to package entire scientific workflows, software and 
libraries, and even data.

For further information see https://sylabs.io/singularity]] )
whatis( [[Compiled with gcc/4.8.5]] )
load("go")
if (mode() ~= "whatis") then
setenv("MAALI_SINGULARITY_HOME","/pawsey/sles12sp3/devel".."/gcc/4.8.5".."/singularity/3.6.4")
prepend_path("PATH","/pawsey/sles12sp3/devel".."/gcc/4.8.5".."/singularity/3.6.4/bin")
setenv("SINGULARITYENV_FI_PROVIDER_PATH","/pawsey/intel/19.0.5/compilers_and_libraries/linux/mpi/intel64/libfabric/lib/prov")
setenv("SINGULARITYENV_I_MPI_ROOT","/pawsey/intel/19.0.5/compilers_and_libraries/linux/mpi")
setenv("SINGULARITYENV_LD_LIBRARY_PATH","/usr/lib64:/pawsey/intel/19.0.5/compilers_and_libraries/linux/mpi/intel64/libfabric/lib:/pawsey/intel/19.0.5/compilers_and_libraries/linux/mpi/intel64/lib/release:/pawsey/intel/19.0.5/compilers_and_libraries/linux/mpi/intel64/lib:$LD_LIBRARY_PATH")
setenv("SINGULARITYENV_OMPI_MCA_btl_openib_allow_ib","1")
setenv("SINGULARITY_BINDPATH","/astro,/group,/scratch,/pawsey,/etc/dat.conf,/etc/libibverbs.d,/usr/lib64/libdaplofa.so.2,/usr/lib64/libdaplofa.so.2.0.0,/usr/lib64/libdat2.so.2,/usr/lib64/libdat2.so.2.0.0,/usr/lib64/libibverbs,/usr/lib64/libibverbs.so,/usr/lib64/libibverbs.so.1,/usr/lib64/libibverbs.so.1.1.14,/usr/lib64/libmlx5.so,/usr/lib64/libmlx5.so.1,/usr/lib64/libmlx5.so.1.1.14,/usr/lib64/libnl-3.so.200,/usr/lib64/libnl-3.so.200.18.0,/usr/lib64/libnl-cli-3.so.200,/usr/lib64/libnl-cli-3.so.200.18.0,/usr/lib64/libnl-genl-3.so.200,/usr/lib64/libnl-genl-3.so.200.18.0,/usr/lib64/libnl-idiag-3.so.200,/usr/lib64/libnl-idiag-3.so.200.18.0,/usr/lib64/libnl-nf-3.so.200,/usr/lib64/libnl-nf-3.so.200.18.0,/usr/lib64/libnl-route-3.so.200,/usr/lib64/libnl-route-3.so.200.18.0,/usr/lib64/librdmacm.so,/usr/lib64/librdmacm.so.1,/usr/lib64/librdmacm.so.1.0.14,/usr/lib64/libnuma.so.1,/usr/lib64/libpciaccess.so.0,/usr/lib64/libpmi.so.0,/usr/lib64/libpmi2.so.0,/usr/lib64/libpsm2.so.2,/usr/lib64/slurm/libslurmfull.so")
setenv("SINGULARITY_CACHEDIR",os.getenv("MYGROUP").."/.singularity")
end

```

**Comment by vsoch** [comment]
okay - to test this I build the container with lmod, and shelled inside:

```bash
docker build -t singularity-hpc .
docker run -it --rm -v $PWD/:/code singularity-hpc
```

Note that the directory with shpc is bound so I can make changes on my host and they will be present in the install in the container at /code. On my host I updated singularity_module to be "singularity" and I wrote a file, singularity.lua, in the root of my modules folder (in the container). I removed the load of go and actually most the file (I would learn the content doesn't really matter as long as it is correct). Then in the container I ran and added an IPython.embed() into the client test so I could test interactively.

```bash
$ shpc test biocontainers/fastqc
```

What happens is that a directory with the container module and a test script are added to tmp, and without any further edits the file looks like this:

```bash
#!/usr/bin/env bash

# This is a testing script that can be populated by a module to ensure that
# it loads. We likely can add additional tests to registry files to run too.

set -e

# This script assumes lmod is setup, and module on the path

export MODULEPATH="/tmp/shpc-test.hxdglbst"
module use "/tmp/shpc-test.hxdglbst"

printf "Testing load of biocontainers/fastqc:v0.11.5\n"
module load "biocontainers/fastqc/v0.11.5"

# TODO add test commands here
```
In my case, I had also added singularity to lmod with a `module use` of a custom folder, so not having it for this shell meant I could reproduce the error. And of course this wouldn't work because my shell here doesn't know about singularity.lua

```bash
#!/usr/bin/env bash

# This is a testing script that can be populated by a module to ensure that
# it loads. We likely can add additional tests to registry files to run too.

set -e

# This script assumes lmod is setup, and module on the path

export MODULEPATH="/tmp/shpc-test.hxdglbst"
module use "/tmp/shpc-test.hxdglbst"
module load singularity

printf "Testing load of biocontainers/fastqc:v0.11.5\n"
module load "biocontainers/fastqc/v0.11.5"

# TODO add test commands here
```

And this worked liked a charm, because of course LMOD knows about singularity.lua under /code/modules.

```bash
#!/usr/bin/env bash

# This is a testing script that can be populated by a module to ensure that
# it loads. We likely can add additional tests to registry files to run too.

set -e

# This script assumes lmod is setup, and module on the path

export MODULEPATH="/tmp/shpc-test.hxdglbst"
module use "/tmp/shpc-test.hxdglbst"
module use "/code/modules"

printf "Testing load of biocontainers/fastqc:v0.11.5\n"
module load "biocontainers/fastqc/v0.11.5"

# TODO add test commands here
~                              
```
```
# ./test.sh 
Testing load of biocontainers/fastqc:v0.11.5
```
So the bug here is that whatever sourcing / module load is done by the tester, it needs to happen in this file as well. Since we don't know the means by which, for example, Singularity is sourced, we might get it wrong. I have never maintained an LMOD install for a user base so I'll have to ask for your advice on this @marcodelapierre  - is there a global / consistent command to ensure that known modules are loadable from this script? I think we have a couple of options:

1. Is it just an issue that we need to preserve a previous modulepath? e.g.,: `export MODULEPATH=/tmp/shpc-test-folder:$MODULEPATH`?
2. If not, we can use some other global setup command in the test.sh script to ensure singularity is found
3. don't add custom module loads to the test script. The current script just tests that the module file loads and is valid, and doesn't interact with the container, so this would work for now, but if we added any container-specific tests (e.g. you could imagine a test section in the container.yaml that has some execution to the container that requires another module to be loaded) then that wouldn't work.
4. Add some custom variable to settings that the registry owner can add to supplement the test files.

What do you think @marcodelapierre ?

**Comment by marcodelapierre** [comment]
I like number 1, bringing the host MODULEPATH in, that's really all we need (for a container testing, appropriate bind mounting will be required).
I find it hard to think of a more general way to achieve the same, because MODULEPATHs can be set at many different levels both by sys admins and users.
The only assumption for the MODULEPATH to work is that the user making use of `shpc test` is in a shell environment where the installed container modules *would* work if used. This could be even briefly said in the docs, and I think it's general for any sub-command of `shpc`: any `module use` or `MODULEPATH` changes required for the container modules to work should always be set up when using `shpc`.

**Comment by vsoch** [comment]
okay I'll try adding that.

**Comment by vsoch** [comment]
This should be fixed - I'll leave open if you want to confirm @marcodelapierre

**Comment by marcodelapierre** [comment]
tested OK with version 0.0.27 !

**Comment by vsoch** [comment]
Phew!
