### ISSUE TITLE
Module files should set Singularity / Podman variables as empty if unset

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-hpc#382]
E.g, if unset for something like nextflow with `set -u`
```
Command error:
  .command.sh: SINGULARITY_OPTS: unbound variable
```
We need to be able to set the variables in the modulefile if they are not defined. This was the fix on the command line for the error above:

```
md@zeus-1:shpc$ export SINGULARITY_OPTS=
md@zeus-1:shpc$ export SINGULARITY_COMMAND_OPTS=
```
I'm not sure how to check definition in the module file but will look into it.

**Comment by marcodelapierre** [comment]
another case apparently.

the bare `csh` (no added charm such as nextflow) does not like unbound variables neither:
```
% samtools 
SINGULARITY_OPTS: Undefined variable.
```

**Comment by marcodelapierre** [comment]
see lmod docs:  https://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html
wondering whether `append_path` could be used with a *null* separator for this purpose

**Comment by marcodelapierre** [comment]
worst case .. modules set them empty, and documentation specifies that those variables must be set after the module is loaded ..?

**Comment by vsoch** [comment]
I understand setting empty for SINGULARITY_OPTS / SINGULARITY_COMMAND_OPTS, but I'm not following the need for append_path?

**Comment by marcodelapierre** [comment]
Oops my comment was a bit confusing!
Was just looking for possible ways of coding the logic `set variables in the modulefile IF they are not defined`.
Saw on the lmod docos (link above) that `append_path` can be used with a 3rd argument being the separator field, so this COULD satisfy our logic: `append_path(SINGULARITY_OPTS, "", "")`.
It would add a null to the existing variable, implicitly creating it if not existing... however, just tested it and it doesn't work, because the 3rd argument MUST be exactly one character long ...

... so forget about this append_path thing :)

**Comment by vsoch** [comment]
This should be fixed.
