### ISSUE TITLE
Minimal comments on Podman/Docker support

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#391]
Hi!
I have just run some quick tests with Podman on Ubuntu 18, and they have worked well!

I just have a couple of minimal comments on the modulefile layout (had a look at LUA modules);
I have used my usual `biocontainers/samtools:v1.9-4-deb_cv1` as a test.

- Some typos in `help screen` -- apply also for Docker

    - `-v ${PWD} -w ${PWD}` is defined also for `<tool>-shell` and `<tool>-exec` but not documented

    - `--entrypoint /bin/sh` is defined for `<tool>-shell` but not documented

    - for `<tool>-exec`, help says `--entrypoint /bin/sh`, but instead it should be `--entrypoint ""`

    - for aliases, e.g. :
      ```
       - samtools:
             podman run --rm -it --entrypoint /usr/bin/samtools --env-file /home/ubuntu/shpc-v0027/modules/biocontainers/samtools/v1.9-4-deb_cv1/99-shpc.sh  -v ${PWD} -w ${PWD} <container> ""
      ```
      Instead of `<container> ""`, the very last bit of this snippet should be `<container> "$@"`.

Only for Podman:

- I notice that the variables here are called `DOCKER_OPTS` and `DOCKER_COMMAND_OPTS`; shouldn't they contain `PODMAN` instead?

PS: the final implementation you used for `entrypoint` is the cleanest possible, love it!

**Comment by vsoch** [comment]
Fixed! (Will come in PR soon). For the environment variable names, since Podman and Docker share the same template file (and the same class base) and Podman is known to be "a shoe in for Docker" - its easier to maintain to just use a standard set of environment variables that both share. As an alternative, we could call them something more generic? It could be something like `OCI_OPTS` and `OCI_COMMAND_OPTS` but I thought that Docker was a more suitable name. What do you think?

**Comment by marcodelapierre** [comment]
>  Podman is known to be "a shoe in for Docker" - its easier to maintain to just use a standard set of environment variables that both share

you're right, makes sense. I was wondering then ... instead of using `DOCKER` for Podman, too ... how about using `PODMAN` for Docker ...? too daring ...? after all SHPC is more focused on HPC, Docker is kind of a free add-on feature
