### ISSUE TITLE
Search for settings.yaml in multiple locations

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#400]
It would be great if SHPC could search in at least 2 distinct locations for `settings.yaml`.
Among other uses, in a shared cluster, this would enable usage of the same central installation of SHPC by both sys. admins. and the end users, with distinct settings.

For instance, drawing inpsiration from Spack, https://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes

I was wondering whether the current one could be the `site` one, and then there could be a `user` one with location in `$USER/.singularity-hpc` or similar. User takes precedence if it exists, only for those keys that are defined in it.

`shpc config` would need something like Spack's `--scope` selector flag.

What do you think @vsoch ?

**Comment by vsoch** [comment]
Hmm so this gets complicated because we are talking about merging settings. I would say that to start we should choose one or the other - if the user has created their own settings, it can first be based off of the central / admin one, and then if found, used exclusively. For spack (personal opinion) I think the design to use settings from all over the place is a bit confusing, and I'm hoping we can avoid it here!

**Comment by vsoch** [comment]
okay finished this up - will have PR later this evening.

**Comment by marcodelapierre** [comment]
Ahah gotcha! I personally like Spack's salad :-D 

But I love the `inituser` approach, based off the current central settings!
