### ISSUE TITLE
"registry" key in settings to support list of values

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#401]
As you can imagine, this can be useful so that a custom registry can be searched, in addition for the registry that ships with SHPC.
A precedence must be established, e.g. higher on the list has higher precedence.

Some more rationale for this.
On one hand I thought, well SHPC container recipes should be universal by definition, and thus should always be pushed and merged into the public registry. So why bother?

On the other hand, I pictured a scenario where a cluster makes a SHPC installation available to all users. 
End users might need to write a new recipe for a container that is not yet supported; I think writing an SHPC recipe is can be taught to a wide range of users. However, instructing them to also open a PR on github is an additional step that may constitute a barrier to some of them. This is a case where a custom location for additional, home-made recipes comes handy.

What do you think @vsoch ?

**Comment by vsoch** [comment]
Yep I think this is totally reasonable - I actually almost did it like this when I first created shpc. The issue is namespace conflict - but as you said, based on the order we can just return the first one found. It might get hairy if someone changes their registry list to have an equivalent identifier in a different place, but probably that's unlikely (and on the user to be careful about!)
