### ISSUE TITLE
shpc load <container>

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-hpc#568]
We should be able to load a container URI, and then given we can parse PATH and the filesystem, come up with a file that takes a best shot at parsing the actual binaries found. Ping @alecbcs 

```bash
$ shpc load ghcr.io/alecbcs/hello
Container ghcr.io/alecbcs/hello has been added to the registry.

$ module load ghcr.io/alecbcs/hello
$ ./hello
Hello World!
```

**Comment by vsoch** [comment]
We now have a workflow associated with the register to completely add a container based on URI, and it uses the guts set of actions, so I'm good to close this issue. Any person that maintains a registry that wants to generate a container.yaml - a "load" - can use this approach.

**Comment by muffato** [comment]
Is it how it's done https://github.com/singularityhub/shpc-registry/blob/main/.github/workflows/new-recipe.yaml#L29-L46 ?
Even if docker is not generally allowed on our cluster, I've got ways of running it ;) (thanks `$DOCKER_HOST` !) so I may be able to run it.

Otherwise, can you explain how one would actually trigger the action / open the PR ?

**Comment by vsoch** [comment]
That's the right workflow! It's a dispatch event so the inputs.* variables come from the little "form" the user fills in when they request it, and you can change those to your on envars, etc.

**Comment by muffato** [comment]
Just tried it on a fork. Amazingly easy to use :)

**Comment by vsoch** [comment]
Thank you!!
