### ISSUE TITLE
pyflakes

### ISSUE THREAD

**Issue by muffato** [singularityhub/singularity-hpc#592]
Hi @vsoch 

As I was running tests, I realised that pyflakes is run on certain files only: https://github.com/singularityhub/singularity-hpc/blob/main/.github/workflows/main.yml#L33-L62 . Most files actually pass pyflakes, and I can make a PR to update the CI.

Just one question about this one: https://github.com/singularityhub/singularity-hpc/blob/main/shpc/client/shell.py#L52-L59
pyflakes complains that the `client` variable is not used anywhere: should it be used in the `embed()` call like for bpython below ?
Otherwise, I'll call `create_client` without storing the return value in `client` to make pyflakes happy

**Comment by vsoch** [comment]
> As I was running tests, I realised that pyflakes is run on certain files only:
For files like `__init__.py` that purposely import (and don't use variables) we skip those - however if we've added to shpc (which we probably have) and forgotten to add entire modules / files that aren't inits, we definitely should.

For https://github.com/singularityhub/singularity-hpc/blob/main/shpc/client/shell.py#L52-L59, client does not appear used, but the way that IPython works is that it will include the local environment, so (akin to the others) the user gets a shell with a client. It doesn't need to be provided to embed or anything like that. We can't call create client without saving to a variable because we do need to provide it to the user, akin to the others.

**Comment by muffato** [comment]
Yep, I noticed that about `__init__.py`
